### ISSUE TITLE
PrepareRelease may create new release checklist issues with wrong labels

### ISSUE THREAD

**Issue by blairconrad** [FakeItEasy/FakeItEasy.Tools#4]
As seen at FakeItEasy/FakeItEasy#1821, which was created with labels "build" and "documentation" instead of ":building_construction: build"  and ":books: documentation".

![image](https://user-images.githubusercontent.com/3275797/111306529-ae8c9b00-862e-11eb-9274-1085edfef761.png)

We should perhaps copy the labels from the old issue instead of just assigning "build" and "documentation" (although these work for the FakeItEasy.Analyzers project).

**Comment by thomaslevesque** [comment]
Oops

> We should perhaps copy the labels from the old issue instead of just assigning "build" and "documentation" (although these work for the FakeItEasy.Analyzers project).

That makes sense.

**Comment by thomaslevesque** [comment]
> (although these work for the FakeItEasy.Analyzers project)

For consistency, we probably should rename the labels in FakeItEasy.Analyzers

**Comment by blairconrad** [comment]
Sure, if you like. I'm of two minds about the labels. The emoji are super cute, but I worry that they hamper accessibility.
What do screenreaders do, e.g.

**Comment by blairconrad** [comment]
I'm working on the change to PrepareRelease.

**Comment by thomaslevesque** [comment]
> The emoji are super cute, but I worry that they hamper accessibility.

It's true. I kinda like the emoji, but I won't fight to keep them.
It would be nice if Github let us specify a symbol for a label, without making it part of the name... Probably too niche to ever be considered, though.

> What do screenreaders do, e.g.

`🏗️ build` is read as "building construction build" by Windows Narrator

**Comment by blairconrad** [comment]
I don't really mind adding the emojis to the Analyzer labels.
